#!/bin/bash

set -e

action=$1
version=$2

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0 || [ 0 -lt 30 ]

  db_input critical baruwa/webserver_type || true
  db_input critical baruwa/webserver/vhost || true
  db_go || true

db_set baruwa/mysql/configure true
db_input critical baruwa/mysql/configure || true
db_go || true

db_get baruwa/mysql/configure || true
if [ "$RET" = "true" ]; then
   db_input critical baruwa/mysql/dbserver || true
   db_input critical baruwa/mysql/dbadmin || true
   db_input critical baruwa/mysql/dbadmpass || true
   db_input critical baruwa/mysql/dbuser || true
   db_input critical baruwa/mysql/dbpass || true
   db_input critical baruwa/mysql/dbname || true
   db_input critical baruwa/django/baruwauser || true
   db_input critical baruwa/django/baruwapass || true
   db_input critical baruwa/django/baruwaemail || true
   db_input critical baruwa/purge || true
   db_go || true
fi
