#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0 || [ $? -lt 30 ]

if [ "$1" = "configure" ]; then

    db_get baruwa/webserver_type
    webservers="$RET"
    restart=""

    for webserver in $webservers; do
	webserver=${webserver%,}
	test -x /usr/sbin/$webserver || continue

	case "$webserver" in
	    apache2)
		if [ -d /etc/$webserver/mods-enabled ]; then
			a2enmod wsgi >/dev/null
		fi
		;;
	esac

	case "$webserver" in
	    apache2)
		test -d /etc/$webserver/sites-available || continue
    		db_get baruwa/webserver/vhost
    		vhost=$RET
    		sed -i -e "s/baruwa-alpha.local/$vhost/" /etc/baruwa/apache.conf
		if [ ! -f /etc/$webserver/sites-available/baruwa -a ! -h /etc/$webserver/sites-available/baruwa ]; then
		    ln -s /etc/baruwa/apache.conf /etc/$webserver/sites-available/baruwa
		fi
		if [ -d /etc/$webserver/sites-enabled ]; then
			a2ensite baruwa >/dev/null
		fi
		restart="$restart $webserver"
		;;
	esac
    done


    db_get baruwa/mysql/configure
    if [ "$RET" = true ]; then

	# get the answers to our questions
	db_get baruwa/mysql/dbserver
	dbserver=$RET
	db_get baruwa/mysql/dbadmin
	dbadmin=$RET
	db_get baruwa/mysql/dbadmpass
	dbadmpass=$RET
	db_get baruwa/mysql/dbname
	dbname=$RET
	db_get baruwa/mysql/dbuser
	dbuser=$RET
	db_get baruwa/mysql/dbpass
	dbpass=$RET
	db_get baruwa/django/baruwauser
	baruwauser=$RET
	db_get baruwa/django/baruwapass
	baruwapass=$RET
	db_get baruwa/django/baruwaemail
	baruwaemail=$RET

	# create the database
	. /usr/share/wwwconfig-common/mysql-createdb.sh
	# create user
	. /usr/share/wwwconfig-common/mysql-createuser.sh
	# grant rights to db
	echo "GRANT ALL ON $dbname.* TO $dbuser@$dbserver IDENTIFIED BY '$dbpass';" > /var/tmp/baruwa-create.sql
	sqlfile="/var/tmp/baruwa-create.sql"
	# run the grants
	. /usr/share/wwwconfig-common/mysql-exec.sh
	# remove credentials
	rm -f /var/tmp/baruwa-create.sql
    fi

    db_stop

    sed -i -e \
    "
    s/DATABASE_NAME = 'baruwa'/DATABASE_NAME = '$dbname'/;
    s/DATABASE_USER = ''/DATABASE_USER = '$dbuser'/;
    s/DATABASE_PASSWORD = ''/DATABASE_PASSWORD = '$dbpass'/;
    s/DATABASE_HOST = ''/DATABASE_HOST = '$dbserver'/;
    " \
    /usr/share/pyshared/baruwa/settings.py
    # populate the database
    /usr/share/pyshared/baruwa/manage.py syncdb --noinput
    # create the admin user
    /usr/share/pyshared/baruwa/manage.py createsuperuser --username $baruwauser --email $baruwaemail --noinput
    # set the password
    export DJANGO_SETTINGS_MODULE=baruwa.settings
    python -c "from django.contrib.auth.models import User;
    user = User.objects.get(username__exact='$baruwauser');
    user.set_password('$baruwapass');user.save()" > /dev/null
    # restart webserver
    for webserver in $restart; do
	webserver=${webserver%,}
	if [ -x /usr/sbin/invoke-rc.d ]; then
	    invoke-rc.d $webserver reload 3>/dev/null || true
	else
	    /etc/init.d/$webserver reload 3>/dev/null || true
	fi
    done
fi

#DEBHELPER#
